name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-scan:
    name: Dependency Scan with pip-audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit

  secret-detection:
  
    name: Secret Detection with TruffleHog OSS
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for deep scanning

      - name: Run TruffleHog full scan and output SARIF
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          scanArguments: --scan-all-branches --report-format sarif
          output: trufflehog.sarif
  
      - name: Upload SARIF to GitHub Security tab
        if: steps.trufflehog.outcome == 'success' || steps.trufflehog.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog.sarif
