name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-scan:
    name: Dependency Scan with pip-audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit

  secret-detection:
     name: Secret Detection with TruffleHog v3
     runs-on: ubuntu-latest

     steps:
        - name: Checkout code
          uses: actions/checkout@v4
              
        - name: Download TruffleHog v3 Binary
          run: |
                curl -L -o trufflehog https://github.com/trufflesecurity/trufflehog/releases/download/v3.64.3/trufflehog_linux_amd64
                chmod +x trufflehog
              
        - name: Run TruffleHog v3 and generate SARIF
          run: |
              ./trufflehog git file://$(pwd) --report-format sarif > trufflehog.sarif
              
        - name: Upload SARIF to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
              sarif_file: trufflehog.sarif
